name: Compatible Typescript Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        typescript-version: [5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Use Node.js 22.x
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.x
    - run: npm ci
    - run: npm run build
    - run: npm install typescript@${{ matrix.typescript-version }}
    - run: npm run ${{ matrix.typescript-version == '6.0' && 'compatibility-test-v6' || 'compatibility-test' }}
